[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
# --strict
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
implicit_reexport = false
strict_equality = true
# --strict end

[tool.black]
max-line-length = 120
target-version = ['py310']
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

# Useful example of pylint configs
# https://github.com/atlassian-api/atlassian-python-api/blob/master/pyproject.toml
[tool.pylint.format]
max-line-length = "120"

[tool.pylint."MESSAGE CONTROL"]
disable = '''
    W0511,
'''