name: Lint

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Format checking with black
      run: |
        black --check src tests
    - name: Sorting imports with isort
      run: |
        isort --check-only src tests
    - name: Type checking with mypy
      run: |
        mypy src
    - name: Static Analysis with pylint
      run: |
        pylint src
    - name: Tests
      run: |
        pytest tests/
